Repository incubateur-ademe/territoires-en-transitions, pull requests merged in 2021-07, with the labels that each got.

#296 Possibilité de commenter les actions des référentiels
  app.territoiresentransitions.fr/src/api/hybridStores.ts
  app.territoiresentransitions.fr/src/components/shared/ActionReferentiel/ActionReferentielCard.svelte
  app.territoiresentransitions.fr/src/components/shared/ActionReferentiel/ActionReferentielCommentaire.svelte
  app.territoiresentransitions.fr/src/components/shared/ActionReferentiel/ProgressStat.svelte
  app.territoiresentransitions.fr/src/components/shared/NavV2/Nav.svelte
  app.territoiresentransitions.fr/src/storables/ActionMetaStorable.ts
  codegen/codegen/codegen/python.py
  codegen/codegen/codegen/typescript.py
  codegen/definitions/shared/action_meta.md
Labels: 🍹 sandbox

#371 [Site statique] Correction favicon mentions légales et image svg sur safari
  territoiresentransitions.fr/src/app.html
  territoiresentransitions.fr/src/components/Markdown/Cards.svelte
Labels: écocopains

#401 Répare les fiches action
  app.territoiresentransitions.fr/src/components/shared/FicheAction/FicheActionCard.svelte
  app.territoiresentransitions.fr/src/routes/fiches/_CategorieForm.svelte
  app.territoiresentransitions.fr/src/routes/fiches/_Form.svelte
  app.territoiresentransitions.fr/src/routes/fiches/creation/index.svelte
  app.territoiresentransitions.fr/src/routes/fiches/index.svelte
Labels: 🍹 sandbox, 🚅 app (production)
